### ISSUE TITLE
Compute Studio Start Year Values

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/Tax-Brain#176]
Tax-Calculator has tax logic back to 2013, but the CPS data are from 2014.  This means that when one tries to run Tax-Brain with start year 2013 selected and selects the CPS as the data source, an error is thrown:

<img width="890" alt="Screen Shot 2021-03-31 at 9 52 13 PM" src="https://user-images.githubusercontent.com/10715924/113232654-93936b00-926b-11eb-9beb-b1f1604e3fc5.png">

I don't know of a way to allow Tax-Calculator to start in a year before the year of the data.  In the long-run, maybe this issue can be resolved in the TaxData package (e.g., allowing one to set the start year of the data), but for now, it would be worth limiting the start year options as a function of the data selected.

cc @hdoupe @andersonfrailey

**Comment by hdoupe** [comment]
Thanks for opening this @jdebacker. It seems like we should add a check to the `taxbrain` package that gives more information about what years are available for a given data source.

For the Compute Studio app, we should update [`get_inputs`](https://github.com/PSLmodels/Tax-Brain/blob/master/cs-config/cs_config/functions.py#L42-L64) to only return 2014 and up when the CPS is selected and have a check in [`validate_inputs`](https://github.com/PSLmodels/Tax-Brain/blob/master/cs-config/cs_config/functions.py#L67-L80) to make sure the start year and data source are consistent.

This would be a good place to use the ParamTools `when` validator (i.e. when data source is CPS start year must be greater than 2014 otherwise must be greater than 2013), but I don't have support for that validator in C/S yet. However, this is good motivation to pick this project back up (https://github.com/PSLmodels/ParamTools/issues/88) to make it easier to keep the JavaScript and Python versions of ParamTools in sync.

**Comment by jdebacker** [comment]
Here's my attempt at a solution over in CCC: https://github.com/PSLmodels/Cost-of-Capital-Calculator/pull/344/files

Tests pass locally, but start years are explicitly tested.

@hdoupe Thoughts?
