### ISSUE TITLE
5 small issues re compmodels version of Tax-Brain

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/Tax-Brain#42]
I apologize if this is the wrong place to comment on the compmodels version of Tax-Brain. I searched for but did not find a place to comment on that. Am putting 5 small comments all together here so that it is easy to move them en masse if they belong elsewhere. If they belong here, I can separate them into individual issues if you want.

I am referring to the interface found [here](https://www.compmodels.org/PSLmodels/Tax-Brain/).

None of these is a significant issue - they are nice-to-haves.

**1. Defining the start year - dropdown preferable to up/down arrows?**
I wanted to look at 2013. The input box shows 2019. Clicking does not show all choices or the earliest year I could use. A dropdown might be nicer because (a) I could see all my choices right away rather than wondering when I could start (I would choose 2011 if I could but Tax-Calculator does not go back that far), and (b) choosing 2013 would be only two clicks (once to see the dropdown, once to choose 2013) rather than the current 7 clicks (once to get into the input box, 6 to lower the year).

**2. User action required to show default parameters for the chosen year**
After choosing my year, I went to the parameters (clicking Personal Income) and scrolled down to see the AMT exemption amount values. They were very unfamiliar, because they were not the actual values for 2013 but for something different. I was afraid to put anything in for fear other things were different, too. Finally, I stumbled onto the idea of going back to the start-year box and hitting enter. That brought up the default parameters for 2013.

Might be better for the users to have the start-year parameters brought up once the year is chosen, or else give them an alert for what they need to do.

**3. Further clickable subdivisions in the parameters interface would be nice.**
In my case, even after clicking on "Personal Income" there was a lot of scrolling to get to the AMT parameters, and some potential for error.

**4. Output distributional table does not start with the start year**
After running my reform, I see a year-by-year change table, which is a nice place to start.

When I scroll down to "Build Table" I see a table that has distributional results, which is nice. Despite two alerts that the output gave me, I initially misinterpreted the table thinking that it was showing me the start year (2013). In fact, it was showing me 2016 - I looked back to the year-by-year change table to be 100% sure. 

The two alerts were:
a) A dropdown prepopulated with the year 2016 (I had seen it but didn't realize it meant that was what the table was). Incidentally, it shows the years out of order - screenshot below:
![image](https://user-images.githubusercontent.com/6538392/57617968-17e18580-7550-11e9-99de-8d36383dc3eb.png)

b) The number 2016 was right there in the table title, which somehow I missed.

I can't say I wasn't forewarned, but still, I'll bet others would expect the start year to be the default year for the distributional table. It might be better to do that, or else do something even more extreme than your 2 alerts to let people know it may not be what they expect. I guess it comes down to how much personal responsibility you want to insist upon.

**5. I did not see the Tax-Calculator version listed in inputs and outputs**
Important to me as I am trying to figure out something that puzzles me in tc cli.

**Comment by andersonfrailey** [comment]
Thanks for the feedback, @donboyd5.

>Output distributional table does not start with the start year

Yes, this is definitely confusing. We've got a patch in the works in PR #40 and should have it live relatively soon.

>Further clickable subdivisions in the parameters interface would be nice.

I see your point here. I'll give this some thought and see how we could break down the parameters further.

>  I did not see the Tax-Calculator version listed in inputs and outputs

This is a good point. I'll add version numbers to PR #40 so that they're included in the next release.

@hdoupe will be able to better help you with points 1 and 2.

**Comment by hdoupe** [comment]
Thanks for the bug report/feedback Don. Some of these issues are on the comp side, or at least should be in the documentation on the COMP side.

1. Good point. @andersonfrailey If the "choice" validator is used, then a drop-down will be used instead of the number box.

2. Ah, I see. It would be nice if there was a suggestion that you needed to hit the reset button to get the new defaults. I found the pop-up box in the previous webapp really annoying when I wanted to set several "meta" parameters at the same time or when I just wanted to change the start year or data source real quick without loading a new page with the new defaults.

3. One solution is to re-organize the inputs to make it easier to click through. Another one would be to somehow expose the subsections in the navbar without cluttering it up, too much. I've tried to do the latter in the past but didn't find a way to do it elegantly.

4. This should be resolved with the new outputs version.

5. I'll add this to the outputs schema. Thanks for the suggestion.

**Comment by donboyd5** [comment]
Thanks. Might also be worth considering, for PR #40, whether you can change the row sort order in the distributional table(s) so that the row-stubs are in order of increasing income (now it must be based on character sort order for the stub names):

![image](https://user-images.githubusercontent.com/6538392/57628191-75350100-7567-11e9-819b-5109648f739a.png)

**Comment by hdoupe** [comment]
@andersonfrailey Items 1, 2, 5 are resolved. I opened an issue for 3 (clickable sub sections) at comp-org/comp-ce#158.

**Comment by andersonfrailey** [comment]
Thanks for the update, @hdoupe. Item 4 has also been resolved as of PR #38.

**Comment by jdebacker** [comment]
I believe this issue can be closed now.  That right, @andersonfrailey?

**Comment by andersonfrailey** [comment]
@jdebacker yep all of this has been taken care of.
